purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4375
  brandStrength: 1
  lightness: 0.25
  brandColors:
    - '#FFFFFF'
    - '#929292'
    - '#ABABAB'
    - '#E1E1E1'
    - '#C2C2C2'
  rhythmicContrast: 0.4444444
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: testv1
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5143369
layout_spectrum: 0.2007169
