name: testv1
favicon: null
layout_spectrum: 0.48447
typography_spectrum: 0.13773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#28272c'
    - '#0c091a'
    - '#4a4a4c'
    - '#7d7d7d'
    - '#c0c0c0'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
